debug: true
updateFreq: 3
faves:
  - category: "animal"
    rank: 3
  - category: "color"
    rank: 2
tools:
  leased: false
  qty: 1
colors:
  - visible: true
    brightness: 10
    name: "red"
  - visible: false
    brightness: 1
    name: "far infrared"
